### ISSUE TITLE
How to run a trained model on a crazyfile?

### ISSUE THREAD

**Issue by AI4IS** [Zhehui-Huang/quad-swarm-rl#61]
I have trained a control model. However, I have no ideas on how to run this model on a real hardware. Are there any ways to help me overcome this problem? Thanks!

**Comment by AI4IS** [comment]
Another question：Should I must need motion capture system if I only want to stablize crazyflie in a fixed position robustly?

**Comment by Zhehui-Huang** [comment]
At the current moment, if you want to deploy a trained model to the real hardware, a motion capture system such as Vicon is required. However, we are working on a version without a motion capture system. If everything goes well, we will open source that version by the end of September or October. At that moment, we will open source the full pipeline.
