### ISSUE TITLE
About the training scripts in ICRA2024 work

### ISSUE THREAD

**Issue by zanghz21** [Zhehui-Huang/quad-swarm-rl#62]
I am not sure which script you used to show the performance in the work "Collision Avoidance and Navigation for a Quadrotor Swarm Using End-to-end Deep Reinforcement Learning." Is it the train_local_obst.sh script? If not, could you please share the correct script?

**Comment by Zhehui-Huang** [comment]
You can use this script: https://github.com/Zhehui-Huang/quad-swarm-rl/blob/master/swarm_rl/runs/obstacles/quad_obstacle_baseline.py.
